#!/usr/bin/env bash
#
# Self-check for scripts/bump-version.sh. It copies your script into a
# temporary project with its own VERSION file, so your real VERSION file is
# never touched. Do not edit this file.
#
# Usage: ./scripts/check-bump.sh

set -uo pipefail

SCRIPT="$(cd "$(dirname "$0")" && pwd)/bump-version.sh"
PASS=0
FAIL=0

check() {
    local description="$1"; shift
    if "$@"; then
        echo "  PASS  $description"
        PASS=$((PASS + 1))
    else
        echo "  FAIL  $description"
        FAIL=$((FAIL + 1))
    fi
}

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Runs the script inside a fresh fake project whose VERSION file holds $1
# (pass NOFILE for "no VERSION file"), with the remaining arguments passed on.
run_bump() {
    local contents="$1"; shift
    rm -rf "$WORK/project" && mkdir -p "$WORK/project/scripts"
    cp "$SCRIPT" "$WORK/project/scripts/bump-version.sh"
    if [ "$contents" != "NOFILE" ]; then
        printf '%s\n' "$contents" > "$WORK/project/VERSION"
    fi
    # Run from a different directory: the script must find VERSION on its own.
    ( cd "$WORK" && bash "$WORK/project/scripts/bump-version.sh" "$@" ) >"$WORK/out" 2>"$WORK/err"
}

version_now() { tr -d '[:space:]' < "$WORK/project/VERSION"; }

echo "Checking $SCRIPT"

# 1. Argument handling
run_bump 2.9.4; code=$?
check "no argument: exits with status 2" test "$code" -eq 2
check "no argument: prints usage to stderr" grep -q "Usage" "$WORK/err"
check "no argument: VERSION unchanged" test "$(version_now)" = "2.9.4"

run_bump 2.9.4 build; code=$?
check "unknown bump type: exits with status 1" test "$code" -eq 1
check "unknown bump type: message on stderr" grep -q "Invalid bump type" "$WORK/err"
check "unknown bump type: VERSION unchanged" test "$(version_now)" = "2.9.4"

run_bump 2.9.4 major extra; code=$?
check "extra argument: exits with status 2" test "$code" -eq 2

# 2. The three bump types
run_bump 2.9.4 patch; code=$?
check "patch: exits with status 0" test "$code" -eq 0
check "patch: 2.9.4 becomes 2.9.5" test "$(version_now)" = "2.9.5"
check "patch: prints 'Bumped 2.9.4 -> 2.9.5'" grep -qx "Bumped 2.9.4 -> 2.9.5" "$WORK/out"

run_bump 2.9.4 minor
check "minor: 2.9.4 becomes 2.10.0 (patch resets)" test "$(version_now)" = "2.10.0"
check "minor: prints 'Bumped 2.9.4 -> 2.10.0'" grep -qx "Bumped 2.9.4 -> 2.10.0" "$WORK/out"

run_bump 2.9.4 major
check "major: 2.9.4 becomes 3.0.0 (minor and patch reset)" test "$(version_now)" = "3.0.0"

run_bump 1.9.9 minor
check "numbers are compared as numbers: 1.9.9 minor becomes 1.10.0" test "$(version_now)" = "1.10.0"

run_bump 0.0.9 patch
check "patch 0.0.9 becomes 0.0.10" test "$(version_now)" = "0.0.10"

# 3. Problems with the VERSION file
run_bump NOFILE patch; code=$?
check "missing VERSION: exits with status 1" test "$code" -eq 1
check "missing VERSION: message on stderr" grep -q "VERSION file not found" "$WORK/err"

run_bump 2.9 patch; code=$?
check "malformed VERSION '2.9': exits with status 1" test "$code" -eq 1
check "malformed VERSION: message on stderr" grep -q "Malformed VERSION" "$WORK/err"
check "malformed VERSION: file left untouched" test "$(version_now)" = "2.9"

run_bump v2.9.4 patch; code=$?
check "malformed VERSION 'v2.9.4': exits with status 1" test "$code" -eq 1

echo
echo "Passed: $PASS   Failed: $FAIL"
[ "$FAIL" -eq 0 ]
